flask_projects/myblog/models.py
"""Database Models"""

from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import Integer, String, Text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):  # pylint: disable=too-few-public-methods
    """SQL Base class"""

    pass  # pylint: disable=unnecessary-pass


db = SQLAlchemy(model_class=Base)


# CONFIGURE TABLE
class BlogPost(db.Model):  # pylint: disable=too-few-public-methods
    """BlogPost DB Class"""

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    title: Mapped[str] = mapped_column(String(250), unique=True, nullable=False)
    subtitle: Mapped[str] = mapped_column(String(250), nullable=False)
    date: Mapped[str] = mapped_column(String(250), nullable=False)
    body: Mapped[str] = mapped_column(Text, nullable=False)
    author: Mapped[str] = mapped_column(String(250), nullable=False)
    img_url: Mapped[str] = mapped_column(String(250), nullable=False)

flask_projects/myblog/app.py
"""My Blog"""

import logging
import os

from flask import Flask
from flask_bootstrap import Bootstrap5
from flask_ckeditor import CKEditor

from models import db
from routes.blogs import blogs_bp

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s"
)

app = Flask(__name__)
ROOTDIR = os.path.dirname(os.path.abspath(__file__))
DB_FILE = os.path.join(ROOTDIR, "instance/posts.db")

app.config["SECRET_KEY"] = "8BYkEfBA6O6donzWlSihBXox7C0sKR6b"
app.config["SQLALCHEMY_DATABASE_URI"] = f"sqlite:///{DB_FILE}"
db.init_app(app)
Bootstrap5(app)
ckeditor = CKEditor(app)
app.register_blueprint(blogs_bp)

# Create DB if doesn't exist
with app.app_context():
    db.create_all()

if __name__ == "__main__":
    app.run(debug=True, port=5000)

flask_projects/myblog/routes/blogs.py
"""Blogs Route"""

import datetime as dt
import logging

from flask import Blueprint, redirect, render_template
from flask_ckeditor import CKEditorField
from flask_wtf import FlaskForm
from sqlalchemy.exc import SQLAlchemyError
from wtforms import StringField, SubmitField
from wtforms.validators import URL, DataRequired

from models import BlogPost, db
from schemas import BlogSchema

blogs_bp = Blueprint("blogs_bp", __name__)

blog_schema = BlogSchema()
blogs_schema = BlogSchema(many=True)


class NewBlogForm(FlaskForm):
    """Form for New Blog"""

    title = StringField("Blog Post Title", validators=[DataRequired()])
    subtitle = StringField("Blog Post Subtitle", validators=[DataRequired()])
    author = StringField("Blog Author Name", validators=[DataRequired()])
    img_url = StringField(
        "Image URL", validators=[DataRequired(), URL(require_tld=True)]
    )
    body = CKEditorField("Blog Content", validators=[DataRequired()])
    add = SubmitField("Add")


@blogs_bp.route("/")
def get_all_posts():
    """Retreive all posts"""

    data = BlogPost.query.all()
    posts = blogs_schema.dump(data)
    return render_template("index.html", all_posts=posts)


@blogs_bp.route("/show/<int:post_id>")
def show_post(post_id):
    """Display Post"""

    requested_post = BlogPost.query.get(post_id)
    print(requested_post)
    return render_template("post.html", post=requested_post)


@blogs_bp.route("/new-post", methods=["GET", "POST"])
def add_new_post():
    """Creates new blog"""

    form = NewBlogForm()

    if form.validate_on_submit():
        new_blog = BlogPost(
            title=form.title.data,
            subtitle=form.subtitle.data,
            date=dt.datetime.today().strftime("%B %d, %Y"),
            body=form.body.data,
            author=form.author.data,
            img_url=form.img_url.data,
        )

        try:
            db.session.add(new_blog)
            db.session.commit()
        except SQLAlchemyError as e:
            logging.error("Failed to add new blog: %s", e)
            db.session.rollback()
            return ("Failed to add blog: %s", {e})

        return redirect("/")

    return render_template("make-post.html", form=form)


@blogs_bp.route("/edit-post/<int:post_id>", methods=["GET", "POST"])
def edit_post(post_id):
    """Edit Post"""

    post = db.get_or_404(BlogPost, post_id)
    print(post)
    form = NewBlogForm(obj=post)

    if form.validate_on_submit():
        post.title = form.title.data
        post.subtitle = form.subtitle.data
        post.body = form.body.data
        post.author = form.author.data
        post.img_url = form.img_url.data

        try:
            db.session.commit()
        except SQLAlchemyError as e:
            logging.error("Failed to update blog: %s", e)
            db.session.rollback()
            return ("Failed to add blog: %s", {e})

        return redirect("/")

    return render_template("make-post.html", form=form)


@blogs_bp.route("/delete/<int:post_id>", methods=["POST"])
def delete_post(post_id):
    """Delete Post"""

    post = db.get_or_404(BlogPost, post_id)

    try:
        db.session.delete(post)
        db.session.commit()
    except SQLAlchemyError as e:
        logging.error("Failed to update blog: %s", e)
        db.session.rollback()
        return ("Failed to add blog: %s", {e})

    return redirect("/")


# Below is the code from previous lessons. No changes needed.
@blogs_bp.route("/about")
def about():
    """About Page"""
    return render_template("about.html")


@blogs_bp.route("/contact")
def contact():
    """Contact Page"""
    return render_template("contact.html")

flask_projects/myblog/templates/contact.html
{% include "header.html" %}

<!-- Page Header-->
<header
  class="masthead"
  style="background-image: url('../static/assets/img/contact-bg.jpg')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          {% if msg_sent: %}
          <h1>Successfully sent your message</h1>
          {% else: %}
          <h1>Contact Me</h1>
          {% endif %}
          <span class="subheading">Have questions? I have answers.</span>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content-->
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <p>
          Want to get in touch? Fill out the form below to send me a message and
          I will get back to you as soon as possible!
        </p>
        <div class="my-5">
          <!-- * * * * * * * * * * * * * * *-->
          <!-- * * Simplified SB Contact Form for the Tutorial* *-->
          <form
            id="contactForm"
            name="sentMessage"
            action="{{ url_for('blogs_bp.contact') }}"
            method="post"
          >
            <div class="form-floating">
              <input
                class="form-control"
                id="name"
                name="name"
                type="text"
                placeholder="Enter your name..."
                required
              />
              <label for="name">Name</label>
            </div>
            <div class="form-floating">
              <input
                class="form-control"
                id="email"
                name="email"
                type="email"
                placeholder="Enter your email..."
                required
              />
              <label for="email">Email address</label>
            </div>
            <div class="form-floating">
              <input
                class="form-control"
                id="phone"
                name="phone"
                type="tel"
                placeholder="Enter your phone number..."
                required
              />
              <label for="phone">Phone Number</label>
            </div>
            <div class="form-floating">
              <textarea
                class="form-control"
                id="message"
                name="message"
                placeholder="Enter your message here..."
                required
                style="height: 12rem"
              ></textarea>
              <label for="message">Message</label>
            </div>
            <br />
            <button
              class="btn btn-danger text-uppercase"
              id="submitButton"
              type="submit"
            >
              NOT USED in Day 67
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</main>

{% include "footer.html" %}

flask_projects/myblog/templates/header.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Clean Blog - Start Bootstrap Theme</title>
    {% block styles %}
    <!-- Load Bootstrap-Flask CSS here -->
    {{ bootstrap.load_css() }}
    <link
      rel="icon"
      type="image/x-icon"
      href="{{ url_for('static', filename='assets/favicon.ico') }}"
    />
    <!-- Font Awesome icons (free version)-->
    <script
      src="https://use.fontawesome.com/releases/v6.3.0/js/all.js"
      crossorigin="anonymous"
    ></script>
    <!-- Google fonts-->
    <link
      href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
      rel="stylesheet"
      type="text/css"
    />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link
      href="{{ url_for('static', filename='css/styles.css') }}"
      rel="stylesheet"
    />
    {% endblock %}
  </head>
  <body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
      <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="/">Start Bootstrap</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarResponsive"
          aria-controls="navbarResponsive"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ms-auto py-4 py-lg-0">
            <li class="nav-item">
              <a
                class="nav-link px-lg-3 py-3 py-lg-4"
                href="{{ url_for('blogs_bp.get_all_posts') }}"
                >Home</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link px-lg-3 py-3 py-lg-4"
                href="{{ url_for('blogs_bp.about') }}"
                >About</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link px-lg-3 py-3 py-lg-4"
                href="{{ url_for('blogs_bp.contact') }}"
                >Contact</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>

flask_projects/myblog/templates/index.html
{% include "header.html" %}

<!-- Page Header-->
<header
  class="masthead"
  style="background-image: url('../static/assets/img/home-bg.jpg')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
          <h1>Clean Blog</h1>
          <span class="subheading">A Blog Theme by Start Bootstrap</span>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content-->
<div class="container px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      <!-- Post preview-->
      {% for post in all_posts %}
      <div class="post-preview">
        <a href="{{ url_for('blogs_bp.show_post', post_id=post.id) }}">
          <h2 class="post-title">{{ post.title }}</h2>
          <h3 class="post-subtitle">{{ post.subtitle }}</h3>
        </a>
        <!-- TODO: Add code to delete posts below -->
        <p class="post-meta">
          Posted by
          <a href="#">{{post.author}}</a>
          on {{post.date}}
          <form method="POST" action="{{ url_for('blogs_bp.delete_post', post_id=post.id) }}" class="d-inline">
            <button type="submit"
                    class="btn btn-link p-0
                          link-offset-2 link-offset-3-hover
                          link-underline link-underline-opacity-0
                          link-underline-opacity-75-hover">
              ✘
            </button>
          </form>

        </p>
      </div>
      <!-- Divider-->
      <hr class="my-4" />
      {% endfor %}

      <!-- New Post -->
      <div class="d-flex justify-content-end mb-4">
      <!-- TODO: Adding new posts -->
        <a
          class="btn btn-primary float-right"
          href="{{ url_for('blogs_bp.add_new_post') }}"
          >Create New Post</a
        >
      </div>

      <!-- Pager-->
      <div class="d-flex justify-content-end mb-4">
        <a class="btn btn-secondary text-uppercase" href="#!">Older Posts →</a>
      </div>
    </div>
  </div>
</div>

{% include "footer.html" %}

flask_projects/myblog/templates/make-post.html
{% from 'bootstrap4/form.html' import render_form %}
{% block content %} {% include "header.html" %}

<!-- Page Header -->
<header
  class="masthead"
  style="background-image: url('../static/assets/img/edit-bg.jpg')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          {% if form.title.data %}
            <h1>Edit Post</h1>
          {% else %}
            <h1>New Post</h1>
          {% endif %}
          <span class="subheading"
            >You're going to make a great blog post!</span
          >
        </div>
      </div>
    </div>
  </div>
</header>

<main class="mb-4">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        {{ render_form(form, novalidate=True, button_map={"submit": "primary"}) }}
        {{ ckeditor.load() }}
        {{ ckeditor.config(name='blog_content') }}
      </div>
    </div>
  </div>
</main>
{% include "footer.html" %} {% endblock %}

flask_projects/myblog/templates/post.html
{% include "header.html" %}

<!-- Page Header-->
<header class="masthead" style="background-image: url('{{post.img_url}}')">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="post-heading">
          <h1>{{ post.title }}</h1>
          <h2 class="subheading">{{ post.subtitle }}</h2>
          <span class="meta"
            >Posted by
            <a href="#">{{ post.author }}</a>
            on {{ post.date }}
          </span>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Post Content -->
<article>
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        {{ post.body|safe }}

        <div class="d-flex justify-content-end mb-4">
          <!-- TODO: Editing posts-->
          <a
            class="btn btn-primary float-right"
            href="{{ url_for('blogs_bp.edit_post', post_id=post.id) }}"
            >Edit Post</a
          >
        </div>
      </div>
    </div>
  </div>
</article>

{% include "footer.html" %}